import React, { useState } from 'react'
import { Plus, Trash2, ChevronDown, ChevronUp, Zap, Loader2, X } from 'lucide-react'

function ProgressIndicator({ progress }) {
  if (!progress) return null
  const pct = progress.total ? Math.round((progress.step / progress.total) * 100) : 0

  return (
    <div className="card border-teal/20 bg-teal/5">
      <div className="flex items-center gap-3 mb-2">
        <Loader2 size={16} className="text-teal animate-spin" />
        <span className="text-sm font-mono text-teal">{progress.message || 'Running evaluation...'}</span>
      </div>
      {progress.total > 0 && (
        <div className="h-1.5 bg-border rounded-full overflow-hidden">
          <div
            className="h-full bg-teal rounded-full transition-all duration-500"
            style={{ width: `${pct}%` }}
          />
        </div>
      )}
    </div>
  )
}

export function EvaluatorForm({ onEvaluate, loading, progress, onCancel }) {
  const [question, setQuestion] = useState('')
  const [answer, setAnswer] = useState('')
  const [contexts, setContexts] = useState([''])
  const [groundTruth, setGroundTruth] = useState('')
  const [showGroundTruth, setShowGroundTruth] = useState(false)
  const [mode, setMode] = useState('full')

  const addContext = () => setContexts((prev) => [...prev, ''])
  const removeContext = (i) =>
    setContexts((prev) => prev.filter((_, idx) => idx !== i))
  const updateContext = (i, val) =>
    setContexts((prev) => prev.map((c, idx) => (idx === i ? val : c)))

  const canSubmit = question.trim() && answer.trim() && contexts.some((c) => c.trim())

  const handleSubmit = (e) => {
    e.preventDefault()
    if (!canSubmit) return
    onEvaluate({
      question: question.trim(),
      answer: answer.trim(),
      contexts: contexts.filter((c) => c.trim()),
      ground_truth: groundTruth.trim() || null,
      mode,
    })
  }

  if (loading) {
    return (
      <div className="space-y-4">
        <ProgressIndicator progress={progress} />
        <button
          onClick={onCancel}
          className="btn-ghost w-full flex items-center justify-center gap-2 text-sm"
        >
          <X size={14} /> Cancel
        </button>
      </div>
    )
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-5">
      {/* Mode selector */}
      <div className="flex items-center gap-3">
        <label className="label mb-0">Eval Mode</label>
        <div className="flex rounded-lg border border-border overflow-hidden">
          {['quick', 'full'].map((m) => (
            <button
              key={m}
              type="button"
              onClick={() => setMode(m)}
              className={`px-4 py-1.5 text-xs font-mono font-semibold transition-colors ${
                mode === m
                  ? 'bg-teal text-bg'
                  : 'text-text-dim hover:text-text hover:bg-border'
              }`}
            >
              {m === 'quick' ? '⚡ Quick' : '🔬 Full'}
            </button>
          ))}
        </div>
      </div>

      {/* Question */}
      <div>
        <label className="label">Question</label>
        <input
          className="input-field"
          placeholder="What is the retrieval-augmented generation approach?"
          value={question}
          onChange={(e) => setQuestion(e.target.value)}
          required
        />
      </div>

      {/* Contexts */}
      <div>
        <div className="flex items-center justify-between mb-1.5">
          <label className="label mb-0">Retrieved Contexts</label>
          <button
            type="button"
            onClick={addContext}
            className="text-xs font-mono text-teal hover:text-teal-dim flex items-center gap-1 transition-colors"
          >
            <Plus size={12} /> Add chunk
          </button>
        </div>
        <div className="space-y-2">
          {contexts.map((ctx, i) => (
            <div key={i} className="flex gap-2">
              <textarea
                className="textarea-field"
                rows={3}
                placeholder={`Context chunk ${i + 1}...`}
                value={ctx}
                onChange={(e) => updateContext(i, e.target.value)}
              />
              {contexts.length > 1 && (
                <button
                  type="button"
                  onClick={() => removeContext(i)}
                  className="text-muted hover:text-red transition-colors flex-shrink-0 mt-1"
                >
                  <Trash2 size={14} />
                </button>
              )}
            </div>
          ))}
        </div>
      </div>

      {/* Answer */}
      <div>
        <label className="label">Generated Answer</label>
        <textarea
          className="textarea-field"
          rows={4}
          placeholder="The answer generated by your RAG system..."
          value={answer}
          onChange={(e) => setAnswer(e.target.value)}
          required
        />
      </div>

      {/* Ground Truth (optional) */}
      <div>
        <button
          type="button"
          onClick={() => setShowGroundTruth((v) => !v)}
          className="flex items-center gap-2 text-xs font-mono text-text-dim hover:text-teal transition-colors"
        >
          {showGroundTruth ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
          Ground Truth (optional — enables context_recall)
        </button>
        {showGroundTruth && (
          <div className="mt-2">
            <textarea
              className="textarea-field"
              rows={3}
              placeholder="The correct reference answer..."
              value={groundTruth}
              onChange={(e) => setGroundTruth(e.target.value)}
            />
          </div>
        )}
      </div>

      <button
        type="submit"
        disabled={!canSubmit || loading}
        className="btn-primary w-full flex items-center justify-center gap-2"
      >
        <Zap size={16} />
        Run Audit
      </button>
    </form>
  )
}
