import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import App from './App'
import { evaluateStream } from './api/client'

vi.mock('./api/client', async () => {
  const actual = await vi.importActual('./api/client')
  return {
    ...actual,
    evaluateStream: vi.fn(),
  }
})

describe('App history flow', () => {
  test('saved evaluations keep the question and can be restored from history', async () => {
    evaluateStream.mockImplementation((_payload, handlers) => {
      handlers.onResult({
        overall_score: 0.91,
        scores: {
          faithfulness: 0.95,
          answer_relevancy: 0.9,
          context_precision: 0.88,
          context_recall: 0.82,
          hallucination_risk: 'low',
        },
        trace: {
          retrieval_stage: { score: 0.85, issues: [] },
          generation_stage: { score: 0.92, issues: [] },
        },
        recommendations: [],
        verdict: 'READY',
        explanation: 'Strong grounding and retrieval quality.',
      })
      return vi.fn()
    })

    render(<App />)

    fireEvent.change(
      screen.getByPlaceholderText('What is the retrieval-augmented generation approach?'),
      { target: { value: 'What is RAG?' } }
    )
    fireEvent.change(
      screen.getByPlaceholderText('The answer generated by your RAG system...'),
      { target: { value: 'RAG combines retrieval with generation.' } }
    )
    fireEvent.change(screen.getByPlaceholderText('Context chunk 1...'), {
      target: { value: 'RAG combines a retriever with a generator.' },
    })

    fireEvent.click(screen.getByRole('button', { name: /Run Audit/i }))

    await waitFor(() => {
      expect(screen.getByText('Strong grounding and retrieval quality.')).toBeInTheDocument()
    })

    fireEvent.click(screen.getByRole('button', { name: /Save/i }))
    fireEvent.click(screen.getByRole('button', { name: /History/i }))

    expect(screen.getByText('What is RAG?')).toBeInTheDocument()

    fireEvent.click(screen.getByText('What is RAG?').closest('button'))

    await waitFor(() => {
      expect(screen.getByDisplayValue('What is RAG?')).toBeInTheDocument()
      expect(screen.getByText('Strong grounding and retrieval quality.')).toBeInTheDocument()
    })
  })
})